name: notes
description: programming and random thoughts
meta_description: "programming and random thoughts"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/notes"
domain_name: "https://tomasroggero.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Tom Roggero"

# Disqus config
disqus-shortname: ""
